config/routes.rb
Rails.application.routes.draw do
  get 'solar_data/welcome'

  post 'solar_data/solar_data'

  root 'solar_data#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/solar_data_controller.rb
class SolarDataController < ApplicationController
  def welcome
  end

  def solar_data
    @data = HTTParty.get("https://api.data.gov/nrel/pvwatts/v5.xml?api_key=#{ENV['SOLAR_API_KEY']}&address=#{params[:address]}&system_capacity=4&azimuth=180&tilt=40&array_type=1&module_type=1&losses=10")
    @address = params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/solar_data_helper.rb
module SolarDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SolarPossibilities</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/solar_data/solar_data.html.erb
<h1>SolarData#solar_data</h1>
<p><%=@address%></p>
<p id="solar-data"><%=@data%></p>

app/views/solar_data/welcome.html.erb
<h1>Welcome!</h1>
<p>Please Enter your Adress</p>
<%= form_tag solar_data_solar_data_path do %>
  <div>
    <%= label_tag :address %>
    <%= text_field_tag :address %>
  </div>

  <%= submit_tag %>
<% end %>